### ISSUE TITLE
Switch deployment to SonaType

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/vectorpipe#117]
In the previous months we have been switching our deployments forgo BinTray and switch ti publishing directly to SonaType (ex: https://github.com/geotrellis/geotrellis-contrib/pull/236)

This gives us SNAPSHOT releases and enables better CI workflow on the projects.
This issue is to switch vectorpipe project similar release structure.

This will probably mean that the group ID for this project will switch from `org.azavea` to `org.azavea.geotrellis`:

https://github.com/geotrellis/vectorpipe/blob/a1ecfc6fc77afd8bb0f2141abb5f532f57b57167/build.sbt#L8

I think this is fine and good, that consistent with the rest of the projects published from `github.com/geotrellis` and reflects the reality that VectorPipe is pretty much part of GeoTrellis ecosystem of tools.

**Comment by CloudNiner** [comment]
Other examples of previous implementations:
- MAML: https://github.com/geotrellis/maml/pull/98, https://github.com/geotrellis/maml/pull/107/files
- GT Server: https://github.com/geotrellis/geotrellis-server/pull/138

This issue requires converting to CircleCI to take advantage of GPG_PASSPHRASE [Example](https://github.com/geotrellis/geotrellis-contrib/pull/236/files#diff-1d37e48f9ceff6d8030570cd36286a61R30) and SonaType credentials [Example](https://github.com/geotrellis/geotrellis-contrib/pull/236/files#diff-fdc3abdfd754eeb24090dbd90aeec2ceR75-R87).

This implementation should be simpler than the GT contrib one, as vectorpipe doesn't require a docker-compose stack to run tests/benchmarks. I'm happy to help isolate what that implies for whoever takes this task.
