### ISSUE TITLE
Vector Tile Pyramiding

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/vectorpipe#14]
For analytics, we will need to be able to stitch vector tiles together. See https://github.com/locationtech/geotrellis/issues/1400

**Comment by fosskers** [comment]
Was this closed in error?

**Comment by lossyrob** [comment]
No, it's a duplicate. See related issue.

**Comment by fosskers** [comment]
We actually don't have an open issue for stitching / pyramiding. The linked issue above is also closed.

**Comment by lossyrob** [comment]
https://github.com/geotrellis/vectorpipe/issues/14

**Comment by lossyrob** [comment]
Ah. I'm confused here. I thought this one was in the GeoTrellis repo

**Comment by fosskers** [comment]
Things to consider while implementing this: 

Pyramiding `RDD`s of Geometries *could* be as simple as taking your RDD (which has no inherant zoom) and using `ClipToGrid` then `Collate` via  a `LayoutDefinition` that represented each zoom you wanted. However, this would probably be garbage for performance, and won't actually be correct. In zooming, one must be conscious of geometry simplification. At what point should should long `Line` (a road, say) be smoothed out to contain less points? When should points be considered "invisible from this height" and disappear altogether?

Futhermore, simplification strategies differ depending on what what VectorTile schema you plan to collate into. For instance, [OpenMapTiles](https://openmaptiles.org/) has specific rules about what kinds of features should appear at each zoom level.

**Comment by fosskers** [comment]
Stitching on the other hand [is an entirely different beast](https://github.com/ngageoint/hootenanny) and probably shouldn't be attempted by VectorPipe directly.

**Comment by jpolchlo** [comment]
Addressed by #67
