### ISSUE TITLE
Nodes may not contain coordinates

### ISSUE THREAD

**Issue by mojodna** [geotrellis/vectorpipe#30]
Not sure why this happens (license change-related redactions?), but these exist (particularly in old data):

```json
{"id":26656529,"type":"node","tags":[],"lat":null,"lon":"214.7483647","nds":[],"members":[],"changeset":13340634,"timestamp":"2012-10-02 14:32:44.0","uid":6567,"user":"bryanovereem","version":3,"visible":false}
```

https://github.com/geotrellis/vectorpipe/blob/b17f1f569d404294ac4091bfb239ffc606556a24/src/main/scala/vectorpipe/osm/package.scala#L77-L78

**Comment by fosskers** [comment]
Note to self: check what the XML parser does too.

**Comment by mojodna** [comment]
I just noticed that longitude is also relative junk: `214.7483647`

**Comment by mojodna** [comment]
(This was the 3rd entry in a Suriname history extract.)

**Comment by mojodna** [comment]
The full history files don't seem to suffer from this, but the process by which Geofabrik extracts are created does.
