### ISSUE TITLE
Read in Files Via Prefix From S3

### ISSUE THREAD

**Issue by jbouffard** [geotrellis/vectorpipe#48]
When reading a file from s3, one can only read a single file at a time. It would be nice, however, if files could be read in via a `prefix` rather than by name. This is similar to GeoTrellis' `S3GeoTiffRDD` which will search/read all files with certain extensions that fall under the given `prefix`. The resulting `RDD` would contain all `Nodes`, `Ways`, and `Relations` from the files that were found.

**Comment by fosskers** [comment]
Do you mean by globs? Passing `s3://foobar/*.orc` currently works.

**Comment by jbouffard** [comment]
Ah, I wasn't aware of that functionality. Yeah, that's pretty similar to what I wanted. The only difference would be that you'd pass `s3://foobar/` instead and it'll just pick up all of the `orc` files for you.

**Comment by fosskers** [comment]
Hadoop handles that automatically, so it might be sufficient to mention the globbing capability in your docs. Does that sound alright?

**Comment by jbouffard** [comment]
Yeah, that would work.
