### ISSUE TITLE
OSM => VectorTiles :: (5) Compacting RDD[(SpatialKey, Seq[Feature[G,D]]] to RDD[(SpatialKey, VectorTile)] 

### ISSUE THREAD

**Issue by fosskers** [geotrellis/vectorpipe#5]
_This is Part 5 of a series of issues documenting the process of creating a world's worth of VectorTiles from OSM Planet data. Please use these issues to discuss solutions._

**Question:** If you know all the geometries to pack into a single `VectorTile`, how do you best separate them into VT `Layer`s? Should Layers be distinguished by OSM tags?

**Comment by fosskers** [comment]
Consider the Cartography used by: https://github.com/omniscale/imposm3

**Comment by fosskers** [comment]
Comment from @lossyrob:

To call it out explicitly, we're looking to construct vector tiles in such a way that would avoid any cartography IP conflicts such as this: osm2vectortiles/osm2vectortiles#387

**Comment by fosskers** [comment]
Comment from @rmrice:

So my understanding of the IP conflict was that osm2vectortiles was using the exact schema of Mapbox Streets in order to be compatible with Mapbox's OSM Bright style, which wasn't intended for use with non-Mapbox products. From the looks of it, they essentially copied a yml file from Mapbox to serve as their schema, which has been deemed a problem.

I am in favor of creating a new schema based off imposm3 that includes all osm features that might be rendered. The imposm3 schema makes the most sense from a cartography standpoint since each table generated would represent a layer in the tileset, and would advocate easy stylesheet creation using CartoCSS. The tables/layers based off this schema would be based of osm keys (landuse, highway, aeroway, water, etc.) with some keys coalesced into one table (so for example the landuse table would include values under keys landuse, amenity, historical, etc.). It would be worth it to go through the imposm3 mapping.yml and identify features that aren't included or any additional layers that would be beneficial. From looking through it a couple of times I noticed that there is only one military feature (military=barracks) and no historical features, which should be included in this new schema we're generating. We would also need to include additional layers for different types of labels (one for roads, one for places, etc.).

Alternatively, I have created a schema in Tilemill (for export as a Mapnik XML) that queries features from an osm database to create layers, which would essentially be the same thing as what we would create using a yml file for vector tiles. The layers I generated for this Mapnik xml style are based on osm keys (landuse, highway, aeroway, water, etc.) with some keys coalesced into one table (like amenity, historical, cultural, and landuse features coalesced into 'type' for table landuse), and includes pretty much anything you might want to render. The only difference is it is querying data from a database created using osm2pgsql rather than imposm. But this could be used to help create a new vector tile schema.

**Comment by fosskers** [comment]
Comment from myself:

That yml file hasn't been removed in master, it seems.

Our plan is to avoid ingestion into a database entirely. @rmrice is your schema something that can be referenced statically to write code off it, or does it necessitate using a DB?

**Comment by fosskers** [comment]
Comment from @lossyrob:

@rmrice great comments, I believe that line of thinking is where we're going.

It seems like what we need in our case is a way to take a yml file, which currently is used to specify schema as either DB tables or vector tiles, and use it in our ingest step to bake these vector tiles. @fosskers I would imagine that this could be wrapped up in some combineByKey step, where vector tiles are build in a streaming way based on some configuration object we derive from this type of yml.

It doesn't seem like the YML for specifying schema is read in a standard way, and also seems to include SQL for some configs; we'd have to figure out a way to specify generic schemas in our processes that match what we need, which doesn't involve SQL queries. I vote keeping YAML just because it seems like that's what the community is used to specifying schemas as.

I will have to look deeper into what imposm3's schema looks, and it would be useful to compare it to other schemas out there. This may be better on the osm2vectortiles ticket (or somewhere we can collaboratively decide on an open OSM schema), but what I'd really like to be able to see is a comparison of all the open schemas currently out there...mapzen's, imposm3's, carto basemaps, and more (tbh I don't understand the field enough to even make a pseudo-comprehensive list). From that we can sort of derive what the current common pieces are out there that should definitely be included, and work to resolve differences by either picking the best, or figuring out how to make aspects of the schema satisfy each of the reasons that those differences exist. @rmrice seems like you know the field better than us, do you have any suggestions on how to accomplish this?

@fosskers it's my understanding that the imposm3 "schema" represents the set of tables that it ingests the vector data into, and what tags it places under what names, and those would roughly correspond to the layers and metadata of vectortiles. Someone please correct me if I'm wrong about that.

**Comment by fosskers** [comment]
Comment from @rmrice:

@fosskers the schema I'm using right now relies on a database that was ingested using osm2pgsql, but results in a package of layers that include all the features we want. I was mostly suggesting that if we do need to query data, I can offer up the queries I'm currently using to use as a base, but if we're avoiding SQL then that probably won't be necessary.

@lossyrob to my knowledge your understanding of the imposm3 schema is correct. It's just a different way to organize OSM features in a database. Rather than sticking all features of one geometry type (point, line, polygon) into the same table, it separates them further to create a table for each OSM key. If an imposm3 database is transformed into vector tiles, it would then result in a layer for each table, or each OSM key (or at least that's how it worked when I was experimenting with tippecanoe>>mbtiles).

I don't think there are too many open schemas out there besides the ones you mentioned, and they are all organized very similarly based off the imposm3 outline. I would like to come up with a schema that includes any feature that might want to be rendered, I'm just not sure how to do this for custom tags. The problem with Mapbox's vector tile schema is that it's pretty watered-down in terms of what feature tags are included. It includes all of the necessary features, which simplifies stylesheet creation for general feature maps, but excludes a lot of features too, which is a problem when creating a cartographic product for certain use cases, and is not very useful for what I am working on here at DG (hence why I want a vector tile set that includes all features ￼ ). Their picking and choosing of which features to include in their schema is their IP, and I don't think we'll have to worry about colliding with that if we include more stuff.

Tagging @Cellington1 because he has done quite a bit of research on vector tiles and might have some insight into creating a schema. And I do think we all agree that ymls are the way to go ￼

**Comment by fosskers** [comment]
Comment from myself:

@rmrice We're confident we can see significant performance increases by avoiding a database, yeah.

> it separates them further to create a table for each OSM key ... it would then result in a layer for each table

A layer per key makes sense. Some general questions:

1. Do we have a master list of de-facto standard keys? Is this it?
2. Should all VTs have the same layers, even if a particular Tile has no Elements of a particular tag? Example: a tile of all forest having an empty highway layer, for conformity.
3. If (2), do we draw a line in the sand for which keys are blessed as standard? If not, (2)'s natural conclusion is for all tiles to have a layer per key that appears anywhere in the world, even if it's custom and only appears once.

While still a work-in-progress, this PR addresses the creation of lossless (in terms of tag information) GeoTrellis Features from OSM Elements. Our current thought is to have a store of "lossless" VTs with all tag data and layers intact, which can then have a .yml-based schema applied to them dynamically for "render-only" VTs, or whatever other kind a user could want.

**Comment by rmrice** [comment]
To answer your first question: the Map Features page is a good reference for acceptable tags and "standard keys," but you have to dig a little deeper to find all keys being used. For example, the main Map Features page includes a section for `man_made` features, including `man_made=tower`, with comment: 
> Please also add a tower:type=* if possible.

So adding an additional tag for key `tower:type` is considered a best practice for tagging a `man_made=tower` feature but is not on the main Map Features page, and instead [has it's own page linked from the main page](http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dtower). So you just have to be careful relying on just that Map Features page to get all acceptable keys and might have to look at additional linked wiki pages. 

[TagInfo](http://taginfo.openstreetmap.org/keys) might be useful for validating most common keys in being used in OSM, but it's a little overwhelming. Looking at the schema for osm2pgsql may also be useful.

LMK if you need help generating a complete list of keys.

I'm not positive about number 2, but I think if you want lighter weight vector tiles you would want to exclude empty layers. [Mapbox put out a blog post about that last week](https://www.mapbox.com/blog/style-optimized-vector-tiles/).

**Comment by fosskers** [comment]
@lossyrob @echeipesh @rmrice 

Alright, time to implement this! So far, the transformations we've been talking about have been applications of schemas onto the raw Geometry collections to split them nicely in different VT `Layer`s.

There are two ways I can see `RDD[(SpatialKey, Seq[OSMFeature])] -> RDD[(SpatialKey, VectorTile)]` happening: 

1. Grind everything down into what we've been calling "Analytic VectorTiles". This probably only has one über `Layer` and isn't doing anything clever about organizing the geometries. Then if you wish to filter them into "Display VectorTiles", we need some function `(VectorTile, Schema) => VectorTile`.

2. Apply a schema right away, so that the output of Step 5 is a VT set with some schema applied. In this scenario, "Analytic VTs" are just the result of some "catch all" schema.

Thoughts? I'm leaning toward the latter.

**Comment by lossyrob** [comment]
As long as the schema application can have a catch-all that says make everything available to a layer (and not have to specify elements), 2. should work. I think we should focus on building the analytic vector tiles before fleshing out too much of the schema generation logic, though.

There perhaps should be some schema to the analytic vector tile, perhaps by geometry type?

**Comment by fosskers** [comment]
Geometries are stored distinct `Feature` types within a VT already (via the spec), but feature types can be freely mixed within a `Layer`. We could do one `Layer` per GT Geom type.

**Comment by fosskers** [comment]
I'm not yet going to bother with the Schema generation and surrounding ceremony; for Analytic VTs we'll use a normal hardcoded function for now.

**Comment by lossyrob** [comment]
Good point about the features being separated already - is there any other extremely generic layout that makes sense? If not one big layer seems like the way to go.

**Comment by fosskers** [comment]
Not unless we analyse the OSM tags, which feels schema-like already. 

Thinking of how our VT codec is implemented, I'm leaning toward one `Layer` per geom type. If you have a `VectorTile` comprised of `LazyLayer`s (the default when decoding) and only wanted access to the Points, you wouldn't have to wait for the codec to grind through any `Line`s or `Polygon`s that were in the way in the linear collection of VT Features.

**Comment by fosskers** [comment]
There is on-going work to be done here (in the realm of supporting other schemas / "Collation functions"), but for now the initial form of this is complete.
