### ISSUE TITLE
Relation Reassociation

### ISSUE THREAD

**Issue by fosskers** [geotrellis/vectorpipe#50]
Currently, the `vectorpipe.osm.features` function takes separate RDDs of the three Element subtypes, regardless of whether they came from an OSM snapshot or full-history file, and yields the expected set of reassociated GeoTrellis Features.

That is, except for MultiPolygons that arise from `Relation` data. In the original "snapshot only" code, relations marked as `type=multipolygon` were handled with some custom Line-reassociation logic. Unfortunately, even without this part of it, the snapshot code as a whole was prohibitively slow. Our matrix of capabilities was thus:

```
| Revision | Nodes -> Points | Ways -> Lines | Ways -> Polygons | Relations -> Polygons | Fast? |
|----------+-----------------+---------------+------------------+-----------------------+-------|
| old      | x               | x             | x                | x                     | *No*  |
| new      | x               | x             | x                |                       | *Yes* |
```

In the recent [OSM + Tobler work](https://github.com/geotrellis/geotrellis-friction-surface/pulls), I used the newer "full-history" logic on a snapshot and the ingest was *significantly* faster, despite some extra logic that usually only concerns actual history files. From this, `features` was made the only user-facing function, and the old `fromSnapshot` was removed.

The `Relations -> Polygons` logic is then yet to be reimplemented. In doing so, please consider the logic/assumptions/caveats present from [this line downward](https://github.com/geotrellis/vectorpipe/blob/c5c2fb26fc60785a72ec829d371ffa95d73d29bc/src/main/scala/vectorpipe/osm/internal/ElementToFeature.scala#L233).

**Comment by jpolchlo** [comment]
After moving to DataFrames, the approach described here became obsolete.  Closing.
