### ISSUE TITLE
Allow the User to Specify the StorageLevel of Internal, Intermediate RDDs

### ISSUE THREAD

**Issue by jbouffard** [geotrellis/vectorpipe#52]
When getting the `Features` from an OSM source, there are internal `RDD`s that hold intermediate data that are cached (see [here](https://github.com/geotrellis/vectorpipe/blob/master/src/main/scala/vectorpipe/osm/internal/PlanetHistory.scala#L54) and [here](https://github.com/geotrellis/vectorpipe/blob/master/src/main/scala/vectorpipe/osm/internal/PlanetHistory.scala#L64-L69)). The `StorageLevel` used for both of these `RDD`s is `MEMORY_ONLY`. However, this causes problems when large amounts of data need to be cached. When this occurs, any spill over is written to disk which slows down the whole process. It would be nice to be able to specify a `StorageLevel` or none at all when reading in `Features`.

**Comment by jbouffard** [comment]
In addition, would it also make sense for these `RDD`s to be `unpersist`ed once used?

**Comment by fosskers** [comment]
I seem to recall that it wasn't possible to unpersist them - some combination of the thing being persisted not being the thing passed back to the user.

**Comment by jbouffard** [comment]
Oh, that's interesting. I'm not sure what would cause that.

Cool. I'll put up a PR soonish that add that in as a parameter.

**Comment by fosskers** [comment]
It was nothing "mechanical" that was preventing it, it was all "structural". Like, the original thing that was marked persisted wasn't visible to the caller, nor was it useful to unpersist the original thing right away in the same method.

**Comment by jpolchlo** [comment]
Now obsolete after move to DataFrames.  Reopen if this is mistaken impression.
