### ISSUE TITLE
Support option to export ring geometries with Mapbox spec compliant winding

### ISSUE THREAD

**Issue by CloudNiner** [geotrellis/vectorpipe#72]
From [Mapbox specification](https://docs.mapbox.com/vector-tiles/specification/#winding-order):

> Any polygon interior ring must be oriented with the winding order opposite that of their parent exterior ring and all interior rings must directly follow the exterior ring to which they belong. Exterior rings must be oriented clockwise and interior rings must be oriented counter-clockwise (when viewed in screen coordinates).

Vector tiles exported that don't provide spec compliant winding can break Mapbox GL JS rendering in subtle ways, such as by incorrectly rendering fill-extrusions: https://github.com/geotrellis/geotrellis-usbuildings/issues/4

**Comment by CloudNiner** [comment]
More generally, this issue could also be expanded to force either CCW or CW winding during export rather than being Mapbox specific.

**Comment by mojodna** [comment]
Does this fix / option belong in GeoTrellis's MVT generation code?

**Comment by jpolchlo** [comment]
That is probably true.  Thoughts, @CloudNiner?

**Comment by CloudNiner** [comment]
Yeah, good point. I'd say that makes more sense. Closing here and reopening a new issue over there.

**Comment by CloudNiner** [comment]
See https://github.com/locationtech/geotrellis/issues/2909
