### ISSUE TITLE
Aggregation / simplification 

### ISSUE THREAD

**Issue by rossbernet** [geotrellis/vectorpipe#73]
To complete the visualizations, we need an aggregation strategy that can handle lower zoom levels.

This demo:

https://demos.azavea.com/building-footprint-elevations/

goes to zoom level 12 I believe.

Tippecannoe may provide guidance:
https://github.com/mapbox/tippecanoe

ArcGIS does it maybe to zoom level 8...
https://www.arcgis.com/home/webmap/viewer.html?useExisting=1&layers=f40326b0dea54330ae39584012807126

But it'd be nice to go even further.

**Comment by jpolchlo** [comment]
What is the feature request here?  The aggregation strategy is considered, from the perspective of the API, to be up to the user.  It may be a bit of a bug/feature situation, but that was the intent.  We can possibly provide some tooling around this, but more likely, a set of examples will be the farthest we go down this road unless there is a clear pattern that we constantly encounter that demands some library functionality.

**Comment by rossbernet** [comment]
Perhaps it's a matter of just running it then?

I thought we needed some additional feature development.

But for the building demo as linked above, I want to understand what needs to be done to enable building footprints to appear up to zoom level...5 or so. The footprints do not need to have information associated with them. But the user should be able to have a sense of relative building density (somewhat similar to the arcgis version linked above)

**Comment by CloudNiner** [comment]
The vector tiles for the demo you linked above are not generated using VectorPipe. It might be possible to retrofit the raster terrain queries into the new VectorPipe API, but I'm not confident in estimates for difficulty or performance in Spark. This should be further discussed offline or over at https://github.com/geotrellis/geotrellis-usbuildings

**Comment by jpolchlo** [comment]
Looking at the arcgis demo, it appears that the building footprints don't appear until either zoom 10 or 11.  At those zoom levels, we do get a vague impression of the buildings, but I can't imagine getting much additional insight at lower levels of detail.  We would probably need to adopt a merging strategy that aggregates nearby buildings into a combined footprint.  That kind of distance-based spatial joining is tough, though.  In these situations, we would usually impose a grid on each tile, convert the building geometries to their centroids and then cluster during the `reduce`, similar to what we do [here](https://github.com/geotrellis/vectorpipe/blob/master/src/test/scala/vectorpipe/vectortile/TestPipeline.scala).  Another strategy that might work is to adopt that binning approach, but replace the building footprints with the convex hull of the contained buildings' centroids?  If the grid cell size is small enough, that might be a viable way of putting together a set of such tiles without having to change how the tiles are displayed (i.e., without having to add a layer in Mapbox GL that has different display behavior, such as a heatmap)?

**Comment by jpolchlo** [comment]
This appears not to be germane to this repo and should be moved to the relevant location suggested by @CloudNiner.
