### ISSUE TITLE
Update to Spark 2.4

### ISSUE THREAD

**Issue by mojodna** [geotrellis/vectorpipe#85]
This isn't a straight drop-in, as Spark's Source v2 API has changed between 2.3 and 2.4. There are some notes in the Sources with some preliminary clues about what needs to be changed.

Benefits of 2.4:

* fixes streaming checkpoints (we have a database workaround for this): https://github.com/azavea/osmesa/issues/88
* "easier" checkpointing (without requiring a Postgres instance)
* introduces various collection-oriented `Column` functions, allowing us to replace / rewrite a number of our UDFs in a more optimized way
* compatibility with newer EMR releases

**Comment by jpolchlo** [comment]
Sounds as if this will preclude VP from being used on older Spark releases, yeah?  Is that a liability?

**Comment by mojodna** [comment]
It might be, depending on other dependencies, yeah.

**Comment by pomadchin** [comment]
Usually `spark-sql` is really sensitive to these minor updates. It is probably makes sense to update just up to the Spark 2.4.2, see the [release notes](https://spark.apache.org/releases/spark-release-2-4-2.html)

**Comment by mojodna** [comment]
This looks like a helpful post on migrating: http://blog.madhukaraphatak.com/migrate-spark-datasource-2.4/
